language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install gcc rake bison git 
env:
  - PROGNAME=hello
before_script:
script:
   - pwd
   - git clone https://github.com/mruby/mruby.git
   - cd mruby 
   - rake 
   - ./bin/mruby --version
   - cd 
   - pwd

